INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('250', 'course', 'user', '[0],[user],', '成长历程', '', '/course', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('251', 'course_list', 'course', '[0],[user],[course],', '成长历程列表', '', '/course/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('252', 'course_add', 'course', '[0],[user],[course],', '成长历程添加', '', '/course/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('253', 'course_update', 'course', '[0],[user],[course],', '成长历程更新', '', '/course/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('254', 'course_delete', 'course', '[0],[user],[course],', '成长历程删除', '', '/course/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('255', 'course_detail', 'course', '[0],[user],[course],', '成长历程详情', '', '/course/detail', '99', '3', '0', NULL, '1', '0');



INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('260', 'message', 'user', '[0],[user],', '报名管理', '', '/message', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('261', 'message_list', 'message', '[0],[user],[message],', '报名管理列表', '', '/message/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('262', 'message_add', 'message', '[0],[user],[message],', '报名管理添加', '', '/message/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('263', 'message_update', 'message', '[0],[user],[message],', '报名管理更新', '', '/message/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('264', 'message_delete', 'message', '[0],[user],[message],', '报名管理删除', '', '/message/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('265', 'message_detail', 'message', '[0],[user],[message],', '报名管理详情', '', '/message/detail', '99', '3', '0', NULL, '1', '0');


INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('270', 'student', 'mgr', '[0],[system],[mgr],', '学员管理', '', '/student', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('271', 'student_list', 'student', '[0],[system],[mgr],[student],', '学员管理列表', '', '/student/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('272', 'student_add', 'student', '[0],[system],[mgr],[student],', '学员管理添加', '', '/student/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('273', 'student_update', 'student', '[0],[system],[mgr],[student],', '学员管理更新', '', '/student/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('274', 'student_delete', 'student', '[0],[system],[mgr],[student],', '学员管理删除', '', '/student/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('275', 'student_detail', 'student', '[0],[system],[mgr],[student],', '学员管理详情', '', '/student/detail', '99', '3', '0', NULL, '1', '0');


INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('280', 'subject', 'subject', '[0],[subject],', '课程管理', '', '/subject', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('281', 'subject_list', 'subject', '[0],[subject],[subject],', '课程管理列表', '', '/subject/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('282', 'subject_add', 'subject', '[0],[subject],[subject],', '课程管理添加', '', '/subject/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('283', 'subject_update', 'subject', '[0],[subject],[subject],', '课程管理更新', '', '/subject/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('284', 'subject_delete', 'subject', '[0],[subject],[subject],', '课程管理删除', '', '/subject/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('285', 'subject_detail', 'subject', '[0],[subject],[subject],', '课程管理详情', '', '/subject/detail', '99', '3', '0', NULL, '1', '0');


INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('290', 'subjectCateory', 'subject', '[0],[subject],', '课程分类管理', '', '/subjectCateory', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('291', 'subjectCateory_list', 'subjectCateory', '[0],[subject],[subjectCateory],', '课程分类管理列表', '', '/subjectCateory/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('292', 'subjectCateory_add', 'subjectCateory', '[0],[subject],[subjectCateory],', '课程分类管理添加', '', '/subjectCateory/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('293', 'subjectCateory_update', 'subjectCateory', '[0],[subject],[subjectCateory],', '课程分类管理更新', '', '/subjectCateory/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('294', 'subjectCateory_delete', 'subjectCateory', '[0],[subject],[subjectCateory],', '课程分类管理删除', '', '/subjectCateory/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('295', 'subjectCateory_detail', 'subjectCateory', '[0],[subject],[subjectCateory],', '课程分类管理详情', '', '/subjectCateory/detail', '99', '3', '0', NULL, '1', '0');


INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('300', 'subjectStuAction', 'subject', '[0],[subject],', '学员选课管理', '', '/subjectStuAction', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('301', 'subjectStuAction_list', 'subjectStuAction', '[0],[subject],[subjectStuAction],', '学员选课管理列表', '', '/subjectStuAction/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('302', 'subjectStuAction_add', 'subjectStuAction', '[0],[subject],[subjectStuAction],', '学员选课管理添加', '', '/subjectStuAction/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('303', 'subjectStuAction_update', 'subjectStuAction', '[0],[subject],[subjectStuAction],', '学员选课管理更新', '', '/subjectStuAction/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('304', 'subjectStuAction_delete', 'subjectStuAction', '[0],[subject],[subjectStuAction],', '学员选课管理删除', '', '/subjectStuAction/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('305', 'subjectStuAction_detail', 'subjectStuAction', '[0],[subject],[subjectStuAction],', '学员选课管理详情', '', '/subjectStuAction/detail', '99', '3', '0', NULL, '1', '0');


INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189826', 'subjectTeaAction', 'subject', '[0],[subject],', '教师课程管理', '', '/subjectTeaAction', '99', '2', '1', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189827', 'subjectTeaAction_list', 'subjectTeaAction', '[0],[subject],[subjectTeaAction],', '教师课程管理列表', '', '/subjectTeaAction/list', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189828', 'subjectTeaAction_add', 'subjectTeaAction', '[0],[subject],[subjectTeaAction],', '教师课程管理添加', '', '/subjectTeaAction/add', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189829', 'subjectTeaAction_update', 'subjectTeaAction', '[0],[subject],[subjectTeaAction],', '教师课程管理更新', '', '/subjectTeaAction/update', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189830', 'subjectTeaAction_delete', 'subjectTeaAction', '[0],[subject],[subjectTeaAction],', '教师课程管理删除', '', '/subjectTeaAction/delete', '99', '3', '0', NULL, '1', '0');
INSERT INTO `guns`.`sys_menu` (`id`, `code`, `pcode`, `pcodes`, `name`, `icon`, `url`, `num`, `levels`, `ismenu`, `tips`, `status`, `isopen`) VALUES ('1002894942106189831', 'subjectTeaAction_detail', 'subjectTeaAction', '[0],[subject],[subjectTeaAction],', '教师课程管理详情', '', '/subjectTeaAction/detail', '99', '3', '0', NULL, '1', '0');
